# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tXVaWlnEgkkm5_QfW9HeU_3y2Y-xioMU
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('Wine.csv')
df.head()

from sklearn.decomposition import PCA

scaler = StandardScaler()
scaled_df = pd.DataFrame(scaler.fit_transform(df))

sns.heatmap(scaled_df.corr())

pca = PCA(n_components=3)
pca.fit(scaled_df)
data_pca = pca.transform(scaled_df)
data_pca = pd.DataFrame(data_pca, columns=['pc1','pc2','pc3'])
data_pca.head()

sns.heatmap(data_pca.corr())