# -*- coding: utf-8 -*-
"""DMV_Assignment_No_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhZOUNv8pv-EeFLtdC6GUYz1Ebugy6pb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/DMV Datasets/online-retail-dataset.csv")

df.head()

df.shape

df.info()

df.describe()

"""# **Null value Detection and removal**"""

df.isna().sum()

required_data = df.drop(['Description', 'CustomerID', 'InvoiceNo'], axis=1)

required_data

required_data.isna().sum()

"""# Group By"""

sales_region = df.groupby('Country')['UnitPrice'].sum()

sales_region

"""# Bar Plot and Pie Plot for sales distribution by region"""

plt.figure(figsize = (8, 8))
sales_region.plot(kind = 'bar')
plt.title("Sales Distribution By Region")
plt.xlabel("Region")
plt.ylabel('Total sales')

plt.figure(figsize = (8, 8))
region = df.groupby('Country')['UnitPrice'].sum()[:5]
region.plot(kind = 'pie')
plt.title("Sales Distribution By Region")

"""# Top performing Region"""

sales_region.idxmax()

"""# Group by country and Quantity"""

len(df['Quantity'].unique())

region_stoke_code = df.groupby(['Country', 'StockCode', 'Quantity'])['UnitPrice'].sum()

region_stoke_code

region_stoke_code = df.groupby(['Country', 'StockCode', 'Quantity'])['UnitPrice'].sum()[:30]

region_stoke_code

region_stoke_code.unstack().plot(kind = 'bar', stacked=True)
plt.title("Sales Comparision with region and quantity")
plt.xlabel('Country')
plt.ylabel('Sales')