# -*- coding: utf-8 -*-
"""DMV4_REAL_ESTATE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxId4hSfQbxYR4U0Hx7hyvfnp2et0I03
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder



df = pd.read_csv('Housing.csv')

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()

fig, axs = plt.subplots(1,3, figsize = (10,3))
plt1 = sns.boxplot(df['price'], ax = axs[0])
plt2 = sns.boxplot(df['area'], ax = axs[1])
plt3 = sns.boxplot(df['bedrooms'], ax = axs[2])

plt.tight_layout()

Q1 = df.price.quantile(0.25)
Q3 = df.price.quantile(0.75)
IQR = Q3 - Q1

df = df[(df.price >= Q1 - 1.5*IQR) & (df.price <= Q3 + 1.5*IQR)]
plt.figure(figsize=(4,4))
plt.boxplot(df.price)
plt.show()

df.head()

for col in df.columns[2:]:
    print(df[col].unique())

cols_to_norm = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']

scaler = MinMaxScaler()
df[cols_to_norm] = scaler.fit_transform(df[cols_to_norm])

df.head()

bool_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating','airconditioning','prefarea']

for col in bool_cols:
    df[col] = df[col].replace({'yes':1,'no':0})

df.head()

df.dtypes

df['furnishingstatus'] = df['furnishingstatus'].astype(str)



df.dtypes

encoder = LabelEncoder()

df['furnishingstatus'] = encoder.fit_transform(df['furnishingstatus'])

df.head()

















































